name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clone Flutter SDK
        run: git clone https://github.com -b stable --depth 1

      - name: Add Flutter to PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Run Flutter Doctor and Get Packages
        run: |
          ./flutter/bin/flutter doctor
          ./flutter/bin/flutter pub get

      - name: Build APK Release
        run: ./flutter/bin/flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
